### PR TITLE
Session data lost during failover issue fixed

### PR DESCRIPTION
**Pull request by zaid-saeedi-khan**
Kindly review changes.

### CODE REVIEW

**Comment by emre-aydin** [comment]
verify

**Comment by emre-aydin** [comment]
Hi @zaid-saeedi-khan 

Thanks for your contribution! Can you also write a test for the fix you're making please? It should be failing without your change applied and passing with your changes applied.

**Comment by emre-aydin** [comment]
verify

**Comment by emre-aydin** [comment]
Hi @zaid-saeedi-khan 

Did you have a chance to write some tests for this?

**Comment by zaid-saeedi-khan** [comment]
No. It will be helpful if someone else can write test cases.

**Comment by emre-aydin** [comment]
I'm closing this pull request as it doesn't have any tests and it's not clear what it fixes.

**Pull request closed without merging**
